version: "3.8"
services:
  tasktacklerapp:
    image: tasktacklerapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - ApiUrl=http://localhost:7213/api/
