name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up environment variables
        run: echo "ApiUrl=${{ secrets.API_URL }}" >> $GITHUB_ENV
      - name: Verify appsettings.json exists
        run: ls -al TaskTackler/appsettings.json
      - name: Replace API URL in appsettings.json
        run: |
          cat TaskTackler/appsettings.json
          jq '.ApiUrl = env.ApiUrl' TaskTackler/appsettings.json > TaskTackler/appsettings.tmp.json
          mv TaskTackler/appsettings.tmp.json TaskTackler/appsettings.json
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i
