name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x" # Or the version you are using
      - name: Restore dependencies
        run: dotnet restore ./TaskTackler
      - name: Set API_URL in appsettings.json
        run: |
          echo "Setting API_URL in appsettings.json"
          jq --arg apiUrl "${{ secrets.API_URL }}" '.ApiUrl = $apiUrl' ./TaskTackler/wwwroot/appsettings.json > ./TaskTackler/wwwroot/appsettings.tmp.json
          mv ./TaskTackler/wwwroot/appsettings.tmp.json ./TaskTackler/wwwroot/appsettings.json
      - name: Build
        run: dotnet build --configuration Release --no-restore ./TaskTackler
      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e., PR comments)
          action: "upload"
          app_location: "./TaskTackler" # App source code path
          output_location: "wwwroot" # Built app content directory - optional
