name: Build TaskTacckler app

on:
  workflow_call:
    inputs:
      resourceGroupName:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true
      API_URL:
        required: true

jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    outputs:
      appServiceAppName: ${{ steps.deploy.outputs.appServiceAppName }}
    steps:
      - uses: actions/checkout@v3
      - name: Sign in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy Bicep file
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          resourceGroupName: ${{ inputs.resourceGroupName }}
          template: Infrastructure/main.bicep
          parameters: >
            apiUrl=${{ secrets.API_URL }}

  build-and-deploy-website:
    needs: deploy-bicep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build application
        run: dotnet build --configuration Release
      - name: Publish application
        run: dotnet publish --configuration Release --output ./publish
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: publish
          path: ./publish
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: publish
      - name: Deploy website
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.deploy-bicep.outputs.appServiceAppName }}
          package: ./publish
